"""empty message

Revision ID: 316f17b36b26
Revises: 
Create Date: 2018-08-09 16:19:59.302919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316f17b36b26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(length=32), nullable=True),
    sa.Column('player_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_data_game_id'), 'game_data', ['game_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_data_game_id'), table_name='game_data')
    op.drop_table('game_data')
    # ### end Alembic commands ###
